<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fundamentos JavaScript</title>
  </head>
  <body>
    <h1>Fundamentos JavaScript</h1>
    <script>
      /* try catch finally */
      // noExiste;
      try {
        console.log("En el Try se agrega el código a evaluar");
        // El try captura el error y lo manda al catch una vez lo detecta
        noExiste;
        console.log("Segundo mensaje en el try");
      } catch (error) {
        console.log("Captura cualquier error surgido en el try");
        console.log(error);
      } finally {
        console.log(
          "El bloque finallly se ejecutara siempre al final de un bloque try-catch"
        );
      }
      try {
        let numero = "a";
        if (isNaN(numero)) {
          throw new Error("El caracter introducido no es un Número");
        }
        console.log(numero * numero);
      } catch (error) {
        console.log(`Se produjo el siguiente error: ${error}`);
      }
    </script>
  </body>
</html>
